CREATE TABLE COREBlog
(
	COREBlogID INT PRIMARY KEY IDENTITY(1,1),	
	BLOGTypeID INT,
	BLOGDetailID INT
)

CREATE TABLE BLOGTypeID
(
	BLOGTypeID INT PRIMARY KEY IDENTITY(1,1),
	BLOGTypeName INT
)

CREATE TABLE BLOGDetail
(
	BLOGDetailID INT PRIMARY KEY IDENTITY(1,1),
	BLOGDetailTitle NVARCHAR(100),
	BLOGDetailSubTitle NVARCHAR(100),
	BLOGDetailImagePath NVARCHAR(250),
	BLOGDetailParagraph NVARCHAR(2000)
)

CREATE TABLE COREPerson
(
	COREPersonID INT PRIMARY KEY IDENTITY(1,1),
	COREPersonName NVARCHAR(50),
	COREPersonSurname NVARCHAR(50),
	COREPersonMobile NVARCHAR(10),
	COREPersonDateOfBirth DATE,
	COREPersonAddressID INT 
)

CREATE TABLE PERSONAddress
(
	PERSONAddressID INT PRIMARY KEY IDENTITY(1,1),
	ADDRESSCountryID INT,
	ADDRESSProvinceID INT,
	ADDRESSSuburbID INT,
	ADDRESSStreetID INT
)

CREATE TABLE ADDRESSCountry
(
	ADDRESSCountryID INT PRIMARY KEY IDENTITY(1,1),
	ADDRESSCOuntryCode VARCHAR(3),
	ADDRESSCountryName VARCHAR(50)
)

CREATE TABLE ADDRESSProvince
(
	ADDRESSProvinceID INT PRIMARY KEY IDENTITY(1,1),
	ADDRESSCountryID INT,
	ADDRESSProvinceName VARCHAR(50)
)

CREATE TABLE ADDRESSSubburb
(
	ADDRESSSuburbID INT PRIMARY KEY IDENTITY(1,1),
	ADDRESSSuburbName VARCHAR(50),
	ADDRESSProvinceID INT
)

CREATE TABLE ADDRESSStreet
(
	ADDRESSStreetID INT PRIMARY KEY IDENTITY(1,1),
	ADDRESStreetName VARCHAR(100),
	ADDRESSStreetCode VARCHAR(10)
)

CREATE TABLE COREMember
(
	COREMemberID INT PRIMARY KEY IDENTITY(1,1),
	COREPersonID INT,
	AspNetUsersID INT
)
